import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
export default function Home () {
  return (
    <div className={styles.container}>
      <Head>
        <title>Construction Company</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <nav className='flex justify-between my-8 font-medium'>
          <h2>Construction Company</h2>{' '}
          <div className='flex gap-x-6 text-sm'>
            <p>Project</p>
            <p>Blog</p>
            <p>Portfolio</p>
            <p>Service</p>
            <p>Services</p>
            <p>Contact</p>
            <p>About</p>
            <p>Home</p>
            <Image
              className=''
              width={24}
              height={24}
              alt='cart'
              src='/media/cart3.svg'
            />
          </div>
        </nav>
      </main>
      <footer className='flex bg-white'>
        <div className='pl-10 pr-28 w-1/2 bg-yellow-500 '>
          <p className='text-2xl font-bold mt-6 mb-8'>Contact Us</p>
          <input
            type='text'
            placeholder='Name'
            className='py-2 px-6 bg-white border-solid'
          />
          <input
            type='text'
            placeholder='Email'
            className='py-2
            px-6
            bg-white
            border-solid ml-10'
          />

          <textarea
            rows={6}
            // cols={60}
            className='bg-white w-full mt-4 resize-none p-2'
            placeholder='Message'
          ></textarea>
          <div className='flex justify-end'>
            <button className='text-white font-medium border-white my-4 border-2 px-5 py-1'>
              Send Message
            </button>
          </div>
        </div>
        <div className='w-2/4'>
          <div className='bg-black w-full flex items-center justify-center gap-x-12 h-20'>
            {' '}
            <Image
              className=''
              width={11}
              height={20}
              alt='facebook'
              src='/vectors/Vector.svg'
            />
            <Image
              className=''
              width={22}
              height={17.94}
              alt='twitter'
              src='/vectors/twitter.svg'
            />
            <Image
              className=''
              width={24}
              height={24}
              alt='linkedin'
              src='/vectors/linkedin.svg'
            />
          </div>
          <div className='mx-16 my-10'>
            <div className='flex gap-x-4'>
              {' '}
              <Image
                width={13.03}
                height={19.46}
                alt='subtract'
                src='/vectors/Subtract.svg'
              />
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </div>
            <div className='flex gap-x-2'>
              {' '}
              <Image
                className=''
                width={19.89}
                height={19.93}
                alt='phone'
                src='/vectors/phone.svg'
              />
              <p>+00 123 456 78</p>
            </div>
            <div className='flex gap-x-2'>
              <Image
                className=''
                width={24}
                height={24}
                alt='mail'
                src='/vectors/mail.svg'
              />
              <p>constractioninc@gmail.com</p>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}
